from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

from screex import __version__
from screex.core import analyzer, mapper, source
from screex.core.manifest import FrameRecord, Manifest

_GENERATED_FRAME_RE = re.compile(
    r"^\d{5}(?:_thumb)?\.(?:png|jpg|jpeg|txt)$", re.IGNORECASE
)
_GENERATED_MARKER = ".screex-generated"


def _log(quiet: bool, msg: str) -> None:
    if not quiet:
        print(msg, file=sys.stderr, flush=True)


def _bounded_float(name: str, value, low: float, high: float) -> float:
    value = float(value)
    if not low <= value <= high:
        raise argparse.ArgumentTypeError(f"{name} must be between {low} and {high}")
    return value


def _positive_float(name: str, value) -> float:
    value = float(value)
    if value <= 0:
        raise argparse.ArgumentTypeError(f"{name} must be greater than 0")
    return value


def _positive_int(name: str, value) -> int:
    value = int(value)
    if value <= 0:
        raise argparse.ArgumentTypeError(f"{name} must be greater than 0")
    return value


def _nonnegative_int(name: str, value) -> int:
    value = int(value)
    if value < 0:
        raise argparse.ArgumentTypeError(f"{name} must be 0 or greater")
    return value


def _nonnegative_float(name: str, value) -> float:
    value = float(value)
    if value < 0:
        raise argparse.ArgumentTypeError(f"{name} must be 0 or greater")
    return value


def _jpeg_quality(value) -> int:
    value = int(value)
    if not 1 <= value <= 100:
        raise argparse.ArgumentTypeError("keyframe quality must be between 1 and 100")
    return value


def _clean_frames_dir(frames_dir: Path) -> None:
    """Remove stale generated frames without deleting user-owned files."""
    if frames_dir.exists():
        marker = frames_dir / _GENERATED_MARKER
        entries = list(frames_dir.iterdir())
        unknown = [
            p.name for p in entries
            if p.name != _GENERATED_MARKER
            and (p.is_dir() or not _GENERATED_FRAME_RE.match(p.name))
        ]
        if unknown:
            sample = ", ".join(sorted(unknown)[:3])
            raise RuntimeError(
                f"refusing to clean {frames_dir}: contains non-Screex files ({sample})"
            )
        if marker.exists():
            shutil.rmtree(frames_dir)
        else:
            for path in entries:
                if path.is_file():
                    path.unlink()
    frames_dir.mkdir(parents=True, exist_ok=True)
    (frames_dir / _GENERATED_MARKER).write_text("generated by screex\n", encoding="utf-8")


def _slow_warning(duration, fps, fast, max_frames, threshold=150):
    """Return a heads-up string if a text-mode index will be slow (many OCR'd frames),
    else None. Text mode OCRs every changed frame, so long/fast-moving video is costly."""
    if fast:
        return None
    est = duration * fps
    if max_frames:
        est = min(est, max_frames)
    if est <= threshold:
        return None
    return (f"~{int(est)} frames to scan in text mode (OCR runs on changed frames) — this can "
            f"take a few minutes. Use --fast (motion-only) or --max-frames to speed it up.")


def _index_has_text(states) -> bool:
    """True if any state captured on-screen text (text mode is meaningful)."""
    return any(getattr(s, "ocr_text", None) for s in states)


def analyze(video, fps=5.0, cols=120, sensitivity=0.06, edge=False, out=None,
            cut_threshold=0.5, max_frames=None, quiet=False):
    import cv2

    video = Path(video)
    info = source.video_info(str(video))
    out_dir = Path(out) if out else video.parent / f"{video.stem}.screex"
    frames_dir = out_dir / "frames"
    _clean_frames_dir(frames_dir)

    records = []
    similarities = []
    prev_gray = None
    last_t = 0.0
    for idx, t, bgr in source.iter_frames(str(video), fps, max_frames=max_frames):
        gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
        score = 0.0 if prev_gray is None else analyzer.motion_score(prev_gray, gray)
        sim = 1.0 if prev_gray is None else analyzer.histogram_similarity(prev_gray, gray)
        prev_gray = gray
        last_t = t
        similarities.append(sim)

        ascii_text = mapper.frame_to_ascii(gray, cols, edge=edge)
        name = f"{idx:05d}"
        png_rel = f"frames/{name}.png"
        txt_rel = f"frames/{name}.txt"
        cv2.imwrite(str(out_dir / png_rel), bgr)
        (out_dir / txt_rel).write_text(ascii_text, encoding="utf-8")

        records.append(FrameRecord(
            idx=idx, t=round(t, 3), score=round(score, 4),
            event=False, ascii=txt_rel, png=png_rel,
        ))
        if not quiet and idx % 25 == 0:
            _log(quiet, f"analyze: {idx + 1} frames...")

    if not records:
        raise ValueError(f"no frames decoded from {video} (empty or unreadable video?)")

    scores = [r.score for r in records]
    times = [r.t for r in records]
    flags = analyzer.flag_events(scores, sensitivity)
    for r, f in zip(records, flags):
        r.event = f
    events = analyzer.group_events(scores, times, flags)
    events = analyzer.classify_events(events, similarities, cut_threshold)

    duration = max(info["duration"], last_t)
    manifest = Manifest(
        video=video.name, duration=round(duration, 3),
        sampled_fps=fps, cols=cols, frames=records, events=events,
    )
    manifest_path = out_dir / "manifest.json"
    manifest.save(manifest_path)
    _log(quiet, f"analyze: {len(records)} frames, {len(events)} events")
    return manifest_path


def _blur_region(bgr, box):
    """Blur a [x, y, w, h] region of a BGR image in place (best-effort)."""
    import cv2

    x, y, w, h = box
    H, W = bgr.shape[:2]
    x0, y0 = max(0, x), max(0, y)
    x1, y1 = min(W, x + w), min(H, y + h)
    if x1 <= x0 or y1 <= y0:
        return
    roi = bgr[y0:y1, x0:x1]
    k = max(3, (min(roi.shape[0], roi.shape[1]) // 2) * 2 + 1)
    bgr[y0:y1, x0:x1] = cv2.GaussianBlur(roi, (k, k), 0)


def index(recording, fps=2.0, change_threshold=0.04, thumb_width=320, out=None,
          max_frames=None, keyframe_format="png", keyframe_quality=90,
          dedupe_threshold=0.95, lang=None, quiet=False,
          text_threshold=0.80, fast=False, motion_epsilon=0.003, ocr_threads=2,
          audio=True, whisper_model="base",
          boxes=False, redact=False, interactions=False, events=False,
          keyframe_budget=None):
    import cv2

    from screex.core import ocr, segment
    from screex.core.index import NarrationSegment, ScreenIndex, ScreenState

    recording = Path(recording)
    info = source.video_info(str(recording))
    warn = _slow_warning(info["duration"], fps, fast, max_frames)
    if warn:
        _log(quiet, f"index: {warn}")
    out_dir = Path(out) if out else recording.parent / f"{recording.stem}.screex"
    frames_dir = out_dir / "frames"
    _clean_frames_dir(frames_dir)

    ext = keyframe_format.lower().lstrip(".")
    if ext not in ("png", "jpg", "jpeg"):
        raise ValueError(f"unsupported keyframe format: {keyframe_format} (use png or jpg)")
    write_params = [cv2.IMWRITE_JPEG_QUALITY, int(keyframe_quality)] if ext in ("jpg", "jpeg") else []

    states: list[ScreenState] = []
    prev_ocr: list[str] = []
    if redact:
        from screex.core import redact as redact_mod
    need_boxes = boxes or redact or interactions or events

    state_boxes = []  # kf boxes parallel to `states` (for interaction labeling)
    last_t = 0.0
    diagnostics: list[str] = []

    def extract_text(bgr):
        return ocr.extract_text(bgr, lang=lang, threads=ocr_threads, diagnostics=diagnostics)

    frames = source.iter_frames(str(recording), fps, max_frames=max_frames,
                                diagnostics=diagnostics)
    tracker = None
    if interactions:
        from screex.core import cursor
        tracker = cursor.CursorTracker(frames)
        frames = iter(tracker)
    if fast:
        segs = segment.segment_stream(frames, change_threshold)
    else:
        segs = segment.segment_by_text(
            frames, extract_text, text_threshold=text_threshold, motion_epsilon=motion_epsilon)
    for seg in segs:
        bgr = seg.frame_bgr
        last_t = seg.t_end

        if need_boxes:
            kf_boxes = ocr.extract_text_boxes(
                bgr, lang=lang, threads=ocr_threads, diagnostics=diagnostics
            )
            text = [b["text"] for b in kf_boxes]
        else:
            kf_boxes = None
            text = seg.ocr_text if seg.ocr_text is not None else extract_text(bgr)

        if redact:
            bgr = bgr.copy()
            red_text = []
            red_boxes = []
            for b in (kf_boxes or [{"text": t, "box": [0, 0, 0, 0]} for t in text]):
                masked, kinds = redact_mod.redact_line(b["text"])
                if kinds and kf_boxes is not None:
                    _blur_region(bgr, b["box"])
                red_text.append(masked)
                red_boxes.append({"text": masked, "box": b["box"]})
            text = red_text
            kf_boxes = red_boxes if kf_boxes is not None else None

        # Merge near-identical consecutive UI states (cheap dedup) instead of emitting
        # a new state + extra image files for what is effectively the same screen.
        if states and ocr.text_similarity(states[-1].ocr_text, text) >= dedupe_threshold:
            states[-1].t_end = round(seg.t_end, 3)
            _log(quiet, f"index: merged near-duplicate state at {seg.t_end:.1f}s")
            continue

        added, removed = ocr.text_diff(prev_ocr, text)
        prev_ocr = text

        name = f"{seg.idx:05d}"
        key_rel = f"frames/{name}.{ext}"
        thumb_rel = f"frames/{name}_thumb.{ext}"
        cv2.imwrite(str(out_dir / key_rel), bgr, write_params)
        th = max(1, int(bgr.shape[0] * thumb_width / bgr.shape[1]))
        cv2.imwrite(str(out_dir / thumb_rel), cv2.resize(bgr, (thumb_width, th)), write_params)

        states.append(ScreenState(
            idx=seg.idx, t_start=round(seg.t_start, 3), t_end=round(seg.t_end, 3),
            thumbnail=thumb_rel, keyframe=key_rel,
            ocr_text=text, text_added=added, text_removed=removed,
            boxes=(kf_boxes or []) if (boxes or events) else [],
        ))
        state_boxes.append(kf_boxes or [])
        _log(quiet, f"index: state {len(states)} @ {seg.t_start:.1f}-{seg.t_end:.1f}s "
                    f"({len(text)} text lines)")

    if not states:
        raise ValueError(f"no UI states produced from {recording} (empty or unreadable video?)")

    narration: list[NarrationSegment] = []
    if interactions and tracker is not None:
        from screex.core import cursor
        fsize = (info["width"], info["height"]) if info["width"] else None
        hits = 0
        for st, bxs in zip(states, state_boxes):
            pt = cursor.hotspot(tracker.positions, st.t_start, st.t_end)
            if pt is None:
                continue
            label = cursor.nearest_label(pt, bxs, frame_size=fsize)
            st.interactions = [{"t": st.t_end, "x": pt[0], "y": pt[1], "label": label}]
            hits += 1
        _log(quiet, f"index: estimated {hits} interaction hotspot(s)")

    if events:
        from screex.core import events as events_mod
        from screex.core import regiondiff
        prev_kf = None
        for i, st in enumerate(states):
            cur_kf = cv2.imread(str(out_dir / st.keyframe))
            region = regiondiff.changed_region(prev_kf, cur_kf) if i > 0 else None
            inter = st.interactions[0] if st.interactions else None
            prev_state = states[i - 1] if i > 0 else st
            try:
                ev = events_mod.classify_event(prev_state, st, region, inter)
            except Exception as exc:  # noqa: BLE001 - never abort indexing on a bad state
                diagnostics.append(f"event classify failed @state {st.idx}: "
                                   f"{type(exc).__name__}: {exc}")
                ev = {}
            if i > 0 and ev:
                st.event = ev
            prev_kf = cur_kf
        # Drop the boxes we only computed to classify, unless the user asked for them.
        if not boxes:
            for st in states:
                st.boxes = []
        _log(quiet, f"index: classified {sum(1 for s in states if s.event)} event(s)")

    if keyframe_budget:
        from screex.core import curate
        sharpness = []
        for st in states:
            kf = cv2.imread(str(out_dir / st.keyframe), cv2.IMREAD_GRAYSCALE)
            sharpness.append(float(cv2.Laplacian(kf, cv2.CV_64F).var()) if kf is not None else 0.0)
        curate.score_states(states, sharpness)
        _log(quiet, f"index: scored salience for {len(states)} state(s); "
                    f"curated budget {keyframe_budget}")

    if audio:
        import screex.core.audio as audio_mod
        if audio_mod.is_available():
            narration = audio_mod.transcribe(str(recording), model=whisper_model)
            if redact:
                from screex.core.index import NarrationSegment
                narration = [NarrationSegment(n.start, n.end, redact_mod.redact_line(n.text)[0])
                             for n in narration]
            _log(quiet, f"index: transcribed {len(narration)} narration segments")
        else:
            _log(quiet, "index: narration skipped — install the audio extra "
                        "(pip install 'screex[audio]') for spoken-word transcripts")

    duration = max(info["duration"], last_t)
    screen_index = ScreenIndex(
        video=recording.name, duration=round(duration, 3),
        sampled_fps=fps, states=states, narration=narration, warnings=diagnostics,
    )
    index_path = out_dir / "index.json"
    screen_index.save(index_path)
    _log(quiet, f"index: {len(states)} states -> {index_path}")
    if not _index_has_text(states):
        _log(quiet, "index: no on-screen text detected — text mode can't split this; "
                    "re-run with --fast for visual (motion) states")
    elif len(states) == 1 and duration > 3:
        _log(quiet, "index: only 1 state for a >3s recording — try a lower "
                    "--text-threshold or a higher --fps (or drop --fast)")
    return index_path


def select_and_export(recording=None, from_index=None, out_dir="keyframes", k=4,
                      query=None, som=False, fps=2.0, quiet=False):
    """Export K curated keyframes from a recording. Query-agnostic by salience
    (``curate.select_curated``) by default; query-conditioned (CLIP relevance) when ``query`` is
    given and the ``[keyframes]`` extra is installed. With ``som``, overlay numbered Set-of-Mark
    boxes (from OCR) onto each. Writes kf_NN.png to ``out_dir``; returns the exported paths."""
    import shutil

    from screex.core import curate
    from screex.core import som as som_mod
    from screex.core.index import ScreenIndex

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    if from_index:
        si = ScreenIndex.load(from_index)
        base = Path(from_index).parent
    else:
        idx_path = index(recording, fps=fps, out=str(out / "_index"), quiet=quiet,
                         audio=False, boxes=True, keyframe_budget=k)
        si = ScreenIndex.load(idx_path)
        base = Path(idx_path).parent
    # Ensure salience exists for the agnostic path (a --from-index built without --keyframe-budget
    # has all-zero salience; score it so selection is meaningful).
    if not any(getattr(s, "salience", 0.0) for s in si.states):
        curate.score_states(si.states, None)

    embedder = None
    if query:
        try:
            embedder = curate.ClipEmbedder()
        except Exception:  # noqa: BLE001 - optional dep / model load; fall back to salience
            _log(quiet, "keyframes: CLIP unavailable, using salience selection")
            embedder = None

    if query and embedder is not None:
        picks = curate.select_curated_for_query(si.states, k, base, query, embedder)
    else:
        picks = curate.select_curated(si.states, k)

    by_kf = {s.keyframe: s for s in si.states}
    exported = []
    for i, pick in enumerate(picks):
        src = base / pick["keyframe"]
        dest = out / f"kf_{i:02d}.png"
        if som:
            st = by_kf.get(pick["keyframe"])
            som_mod.annotate(str(src), getattr(st, "boxes", []) or [], str(dest))
        else:
            shutil.copyfile(str(src), str(dest))
        exported.append(str(dest))
    _log(quiet, f"keyframes: exported {len(exported)} -> {out}")
    return exported


def main(argv=None):
    # Transcripts and progress can contain non-ASCII (emoji, OCR'd unicode); avoid
    # crashing on legacy consoles (e.g. Windows cp1252) when printing to stdout/stderr.
    for stream in (sys.stdout, sys.stderr):
        try:
            if not hasattr(stream, "reconfigure"):
                continue
            stream.reconfigure(encoding="utf-8")
        except Exception:
            pass

    p = argparse.ArgumentParser(prog="screex")
    p.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    p.add_argument("-q", "--quiet", action="store_true", help="suppress progress output")
    sub = p.add_subparsers(dest="cmd", required=True)

    a = sub.add_parser("analyze", help="analyze a video into ASCII frames + manifest")
    a.add_argument("video")
    a.add_argument("--fps", type=lambda v: _positive_float("fps", v), default=5.0,
                   help="frames sampled per second")
    a.add_argument("--cols", type=lambda v: _positive_int("cols", v), default=120,
                   help="ASCII grid width")
    a.add_argument("--sensitivity", type=lambda v: _bounded_float("sensitivity", v, 0.0, 1.0),
                   default=0.06,
                   help="motion threshold (0..1) for flagging event frames")
    a.add_argument("--edge", action="store_true", help="emphasize edges/structure")
    a.add_argument("--out", default=None, help="output dir (default <video>.screex)")
    a.add_argument("--cut-threshold", type=lambda v: _bounded_float("cut threshold", v, 0.0, 1.0),
                   default=0.5,
                   help="histogram-similarity below which an event is a scene cut (0..1)")
    a.add_argument("--max-frames", type=lambda v: _positive_int("max frames", v), default=None,
                   help="cap the number of sampled frames")

    ix = sub.add_parser("index", help="build a ScreenIndex from a screen recording")
    ix.add_argument("recording")
    ix.add_argument("--fps", type=lambda v: _positive_float("fps", v), default=2.0,
                    help="frames sampled per second")
    ix.add_argument("--change-threshold",
                    type=lambda v: _bounded_float("change threshold", v, 0.0, 1.0),
                    default=0.04,
                    help="mean frame-to-frame intensity change (0..1) that marks a new UI "
                         "state; also triggers on cumulative drift from the state anchor")
    ix.add_argument("--thumb-width", type=lambda v: _positive_int("thumb width", v), default=320,
                    help="thumbnail width in px")
    ix.add_argument("--out", default=None, help="output dir (default <recording>.screex)")
    ix.add_argument("--max-frames", type=lambda v: _positive_int("max frames", v), default=None,
                    help="cap the number of sampled frames")
    ix.add_argument("--keyframe-format", default="png", choices=["png", "jpg", "jpeg"],
                    help="image format for keyframes/thumbnails (jpg is much smaller)")
    ix.add_argument("--keyframe-quality", type=_jpeg_quality, default=90,
                    help="JPEG quality 1..100 (only used with jpg)")
    ix.add_argument("--dedupe-threshold", type=lambda v: _nonnegative_float("dedupe threshold", v),
                    default=0.95,
                    help="merge consecutive states whose on-screen text is at least this "
                         "similar (0..1); set to >1 to disable merging")
    ix.add_argument("--lang", default=None, help="OCR language hint (default: auto)")
    ix.add_argument("--text-threshold",
                    type=lambda v: _bounded_float("text threshold", v, 0.0, 1.0),
                    default=0.80,
                    help="start a new state when on-screen text similarity drops below this (0..1)")
    ix.add_argument("--motion-epsilon",
                    type=lambda v: _bounded_float("motion epsilon", v, 0.0, 1.0),
                    default=0.003,
                    help="skip OCR on frames whose motion vs the previous frame is below this")
    ix.add_argument("--fast", action="store_true",
                    help="motion-only segmentation (no per-frame OCR); faster but misses subtle changes")
    ix.add_argument("--ocr-threads", type=lambda v: _nonnegative_int("ocr threads", v), default=2,
                    help="onnxruntime intra-op threads for OCR (2 is fastest on most CPUs; "
                         "0 = library default)")
    ix.add_argument("--no-audio", action="store_true",
                    help="skip speech-to-text narration (faster; on by default when "
                         "'screex[audio]' is installed)")
    ix.add_argument("--whisper-model", default="base",
                    help="faster-whisper model for narration (tiny/base/small/medium)")
    ix.add_argument("--boxes", action="store_true",
                    help="include per-line OCR bounding boxes [x,y,w,h] in each state")
    ix.add_argument("--redact", action="store_true",
                    help="mask secrets/PII (keys, emails, tokens, cards) in text and "
                         "narration, and blur those regions in keyframes")
    ix.add_argument("--interactions", action="store_true",
                    help="estimate per-state cursor/interaction hotspots (heuristic) and "
                         "label them with the nearest on-screen text")
    ix.add_argument("--events", action="store_true",
                    help="classify each state transition into a typed action event "
                         "(navigate/type/click/open_dialog/error/scroll/edit)")
    ix.add_argument("--keyframe-budget", type=lambda v: _positive_int("keyframe budget", v),
                    default=None,
                    help="score each state's salience (text-change + keyframe sharpness + event) "
                         "so compact_dict can surface the N most informative curated keyframes")

    c = sub.add_parser("capture", help="record a short clip from the screen or webcam")
    capture_source = c.add_mutually_exclusive_group()
    capture_source.add_argument("--screen", action="store_true", help="capture the screen (needs 'mss')")
    capture_source.add_argument("--webcam", action="store_true", help="capture the default webcam")
    c.add_argument("--seconds", type=lambda v: _positive_float("seconds", v), default=10.0)
    c.add_argument("--fps", type=lambda v: _positive_float("fps", v), default=None,
                   help="capture frames per second (default: screen 10, webcam 15)")
    c.add_argument("--monitor", type=lambda v: _positive_int("monitor", v), default=1,
                   help="screen monitor number for --screen (1 = primary)")
    c.add_argument("--device", type=lambda v: _nonnegative_int("device", v), default=0,
                   help="webcam device index for --webcam/default capture")
    c.add_argument("--out", default="capture.mp4")

    sk = sub.add_parser("skill", help="install or locate the Screex Claude skill (SKILL.md)")
    sk.add_argument("--install", action="store_true",
                    help="copy the bundled SKILL.md into the skills dir (default action)")
    sk.add_argument("--dir", default=None,
                    help="target skills dir (default ~/.claude/skills/screex)")
    sk.add_argument("--path", action="store_true",
                    help="print the install target path without writing")
    sk.add_argument("--check", action="store_true",
                    help="report whether the installed skill matches this package version")

    tr = sub.add_parser("transcript", help="build a markdown step transcript from a recording")
    tr.add_argument("recording", nargs="?",
                    help="recording to index; optional when --from-index is provided")
    tr.add_argument("-o", "--out", default=None, help="markdown output file (default: stdout)")
    tr.add_argument("--from-index", default=None,
                    help="use an existing index.json instead of building one")
    tr.add_argument("--fps", type=lambda v: _positive_float("fps", v), default=2.0,
                    help="frames sampled per second")
    tr.add_argument("--text-threshold",
                    type=lambda v: _bounded_float("text threshold", v, 0.0, 1.0),
                    default=0.80,
                    help="text-similarity threshold for a new state (0..1)")
    tr.add_argument("--fast", action="store_true", help="motion-only segmentation when building")
    tr.add_argument("--no-audio", action="store_true", help="skip speech-to-text narration")
    tr.add_argument("--whisper-model", default="base", help="faster-whisper model for narration")
    tr.add_argument("--redact", action="store_true", help="mask secrets/PII when building the index")
    tr.add_argument("--interactions", action="store_true",
                    help="estimate cursor/interaction hotspots and show them in the transcript")
    tr.add_argument("--events", action="store_true",
                    help="classify and render typed action events in the transcript")
    tr.add_argument("--format", choices=["md", "json", "srt", "vtt"], default="md",
                    help="output format: md (default), json (compact index), srt, or vtt")

    nf = sub.add_parser("info", help="summarize a built index.json")
    nf.add_argument("index", help="path to an index.json")
    nf.add_argument("--json", action="store_true", help="print the summary as JSON")

    se = sub.add_parser("search", help="search states in a built index.json")
    se.add_argument("index", help="path to an index.json")
    se.add_argument("pattern", nargs="?", default=None,
                    help="case-insensitive text to find in on-screen text")
    se.add_argument("--since", type=float, default=None, help="only states at/after this time (s)")
    se.add_argument("--until", type=float, default=None, help="only states at/before this time (s)")
    se.add_argument("--event", default=None,
                    help="only states with this typed event (navigate/type/click/...)")
    se.add_argument("--json", action="store_true", help="print hits as JSON")

    sub.add_parser("mcp", help="run the Screex MCP server over stdio (needs 'screex[mcp]')")

    kf = sub.add_parser("keyframes",
                        help="export K curated (optionally set-of-mark) keyframes from a recording")
    kf.add_argument("recording", nargs="?",
                    help="recording to index (omit if using --from-index)")
    kf.add_argument("--from-index", default=None,
                    help="reuse an existing index.json (build it with --boxes for --som)")
    kf.add_argument("--k", type=lambda v: _positive_int("k", v), default=4,
                    help="number of keyframes to export")
    kf.add_argument("--query", default=None,
                    help="question to select keyframes by CLIP relevance (needs the [keyframes] extra)")
    kf.add_argument("--som", action="store_true",
                    help="overlay numbered set-of-mark boxes from OCR onto the keyframes")
    kf.add_argument("--fps", type=lambda v: _positive_float("fps", v), default=2.0,
                    help="sampling fps when building the index")
    kf.add_argument("--out", default="keyframes", help="output directory for exported keyframes")

    args = p.parse_args(argv)
    quiet = getattr(args, "quiet", False)
    if args.cmd == "analyze":
        path = analyze(args.video, fps=args.fps, cols=args.cols,
                       sensitivity=args.sensitivity, edge=args.edge, out=args.out,
                       cut_threshold=args.cut_threshold, max_frames=args.max_frames,
                       quiet=quiet)
        print(f"manifest: {path}")
    elif args.cmd == "index":
        path = index(args.recording, fps=args.fps, change_threshold=args.change_threshold,
                     thumb_width=args.thumb_width, out=args.out, max_frames=args.max_frames,
                     keyframe_format=args.keyframe_format, keyframe_quality=args.keyframe_quality,
                     dedupe_threshold=args.dedupe_threshold, lang=args.lang, quiet=quiet,
                     text_threshold=args.text_threshold, motion_epsilon=args.motion_epsilon,
                     fast=args.fast, ocr_threads=args.ocr_threads,
                     audio=not args.no_audio, whisper_model=args.whisper_model,
                     boxes=args.boxes, redact=args.redact, interactions=args.interactions,
                     events=args.events, keyframe_budget=args.keyframe_budget)
        print(f"index: {path}")
    elif args.cmd == "capture":
        if args.screen:
            fps = args.fps if args.fps is not None else 10.0
            out = source.capture_screen(args.out, args.seconds, fps=fps, monitor=args.monitor)
        else:
            fps = args.fps if args.fps is not None else 15.0
            out = source.capture_webcam(args.out, args.seconds, fps=fps, device=args.device)
        print(f"captured: {out}")
    elif args.cmd == "skill":
        from screex import skill as skill_mod
        target_dir = Path(args.dir) if args.dir else skill_mod.default_skill_dir()
        skill_path = target_dir / "SKILL.md"
        if args.check:
            status = skill_mod.skill_status(args.dir)
            if status == "current":
                print(f"skill up to date ({__version__}): {skill_path}")
            elif status == "missing":
                print("skill not installed — run: screex skill --install")
            else:
                print(f"skill out of date — run: screex skill --install  ({skill_path})")
        elif args.path:
            print(skill_path)
        else:
            target = skill_mod.install_skill(args.dir)
            print(f"installed skill: {target}")
    elif args.cmd == "transcript":
        from screex.core.index import ScreenIndex
        from screex.transcript import FORMATTERS
        if args.from_index:
            si = ScreenIndex.load(args.from_index)
        else:
            if not args.recording:
                p.error("transcript requires a recording unless --from-index is provided")
            idx_path = index(args.recording, fps=args.fps, text_threshold=args.text_threshold,
                             fast=args.fast, quiet=quiet,
                             audio=not args.no_audio, whisper_model=args.whisper_model,
                             redact=args.redact, interactions=args.interactions,
                             events=args.events)
            si = ScreenIndex.load(idx_path)
        rendered = FORMATTERS[args.format](si)
        if args.out:
            Path(args.out).write_text(rendered, encoding="utf-8")
            print(f"transcript: {args.out}")
        else:
            print(rendered)
    elif args.cmd == "info":
        import json as _json

        from screex.core.index import ScreenIndex
        from screex.query import summarize_index
        summary = summarize_index(ScreenIndex.load(args.index))
        if args.json:
            print(_json.dumps(summary, indent=2))
        else:
            for k, v in summary.items():
                print(f"{k}: {v}")
    elif args.cmd == "search":
        import json as _json

        from screex.core.index import ScreenIndex
        from screex.query import search_index
        hits = search_index(ScreenIndex.load(args.index), pattern=args.pattern,
                            since=args.since, until=args.until, event_type=args.event)
        if args.json:
            print(_json.dumps(hits, indent=2))
        else:
            for h in hits:
                tag = f" [{h['event']}]" if h["event"] else ""
                extra = f"  {h['matches']}" if h["matches"] else ""
                print(f"state {h['idx']}  {h['t_start']:.1f}-{h['t_end']:.1f}s{tag}{extra}")
            print(f"# {len(hits)} state(s)", file=sys.stderr)
    elif args.cmd == "mcp":
        from screex import mcp_server
        try:
            mcp_server.serve()
        except RuntimeError as exc:
            p.error(str(exc))
    elif args.cmd == "keyframes":
        if not args.recording and not args.from_index:
            p.error("keyframes requires a recording unless --from-index is provided")
        exported = select_and_export(
            recording=args.recording, from_index=args.from_index, out_dir=args.out,
            k=args.k, query=args.query, som=args.som, fps=args.fps, quiet=quiet)
        for path in exported:
            print(path)


if __name__ == "__main__":
    main()
